apiVersion: apps/v1
kind: Deployment
metadata:
  name: lcrm-backend-deployment
  labels:
    app: lcrm-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lcrm-backend
  template:
    metadata:
      labels:
        app: lcrm-backend
    spec:
      containers:
      - name: lcrm-backend
        image: lcrm-backend:1.1
        env:
        - name: DB_HOST
          value: postgres-service

        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lcrm-backend-service
spec:
  selector:
    app: lcrm-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
