apiVersion: apps/v1
kind: Deployment
metadata:
  name: lcrm-frontend-deployment
  labels:
    app: lcrm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lcrm-frontend
  template:
    metadata:
      labels:
        app: lcrm-frontend
    spec:
      containers:
      - name: lcrm-frontend
        image: lcrm-frontend:1.0
        env:
        - name: BASE_URL
          value: http://lcrm-backend-service::8080/api/v1

        imagePullPolicy: Never
        ports:
        - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: lcrm-frontend-service
spec:
  selector:
    app: lcrm-frontend
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
  type: NodePort
